#!/usr/bin/env bash
# One-shot installer for the Gemma menu-bar app.
# Sets up llama.cpp (clone + build, or reuse an existing build) and builds the app.
# You should not need to touch llama.cpp yourself.
set -euo pipefail

PROJ="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TARGET_DIR="$PROJ/llama.cpp-mainline"
BIN="$TARGET_DIR/build/bin/llama-server"

# Defaults (override by exporting before running, e.g. GEMMA_PORT=9000 ./install.sh)
MODEL_HOME="${GEMMA_MODEL_DIR:-$HOME/.cache/gemma-server/models}"
MODEL="${GEMMA_MODEL:-$MODEL_HOME/gemma-4-12b-it-qat-q4_0.gguf}"
MMPROJ="${GEMMA_MMPROJ:-$MODEL_HOME/mmproj-gemma-4-12b-it-qat-q4_0.gguf}"
HOST="${GEMMA_HOST:-0.0.0.0}"
PORT="${GEMMA_PORT:-8080}"
CTX="${GEMMA_CTX:-32768}"
HF_REPO="${GEMMA_HF_REPO:-google/gemma-4-12B-it-qat-q4_0-gguf}"

say() { printf "\033[1;36m▸ %s\033[0m\n" "$*"; }
warn() { printf "\033[1;33m! %s\033[0m\n" "$*"; }
banner() { # banner <title> <line...>
  printf "\n\033[1;35m┌─────────────────────────────────────────────────────────────┐\033[0m\n"
  printf "\033[1;35m│\033[0m \033[1m%-59s\033[0m \033[1;35m│\033[0m\n" "$1"; shift
  for l in "$@"; do printf "\033[1;35m│\033[0m %-59s \033[1;35m│\033[0m\n" "$l"; done
  printf "\033[1;35m└─────────────────────────────────────────────────────────────┘\033[0m\n"
}

[ "$(uname)" = "Darwin" ] || { echo "This installer is macOS-only."; exit 1; }

# ---- 1. llama.cpp ---------------------------------------------------------
if [ -x "$BIN" ]; then
  say "llama-server already built — reusing it."
else
  if ! command -v cmake >/dev/null 2>&1; then
    if command -v brew >/dev/null 2>&1; then
      say "Installing cmake via Homebrew…"; brew install cmake
    else
      echo "cmake is required to build llama.cpp. Install Homebrew (https://brew.sh) then re-run, or run: brew install cmake"
      exit 1
    fi
  fi
  banner "One-time setup: building llama.cpp" \
         "This downloads + compiles llama.cpp with Metal." \
         "Expect roughly 5-15 minutes. Progress is shown below." \
         "You only pay this cost once."
  if [ ! -d "$TARGET_DIR/.git" ] && [ ! -L "$TARGET_DIR" ]; then
    say "Cloning llama.cpp…"
    git clone --depth 1 --progress https://github.com/ggml-org/llama.cpp "$TARGET_DIR"
  fi
  say "Configuring (cmake)…"
  cmake -B "$TARGET_DIR/build" -S "$TARGET_DIR" \
    -DCMAKE_BUILD_TYPE=Release -DGGML_METAL=ON -DLLAMA_CURL=OFF -DLLAMA_BUILD_SERVER=ON
  say "Compiling — the [ NN%] markers below are your progress bar:"
  cmake --build "$TARGET_DIR/build" -j --target llama-server llama-cli
fi

# ---- 2. Model — try to download, otherwise point the user to it ----------
hf_download() { # hf_download <remote-filename> <dest-path>  → 0 on success
  local file="$1" dest="$2"
  [ -f "$dest" ] && return 0
  mkdir -p "$(dirname "$dest")"
  local token="${HF_TOKEN:-${HUGGING_FACE_HUB_TOKEN:-}}"
  local auth=(); [ -n "$token" ] && auth=(-H "Authorization: Bearer $token")
  say "Downloading $file …"
  # Note the ${arr[@]+"${arr[@]}"} guard: under `set -u`, macOS bash 3.2 errors on
  # expanding an empty array, so we only expand auth when it actually has elements.
  if curl -fL --progress-bar ${auth[@]+"${auth[@]}"} \
       -o "$dest.part" "https://huggingface.co/$HF_REPO/resolve/main/$file?download=true"; then
    mv "$dest.part" "$dest"; return 0
  fi
  rm -f "$dest.part"; return 1
}

if [ ! -f "$MODEL" ] || [ ! -f "$MMPROJ" ]; then
  banner "One-time setup: downloading the model" \
         "The Gemma weights are several GB (~8 GB total)." \
         "This can take a while on a slow connection." \
         "A progress bar with speed/ETA is shown for each file."
  say "Fetching from Hugging Face ($HF_REPO)…"
  ok=1
  hf_download "$(basename "$MODEL")"  "$MODEL"  || ok=0
  hf_download "$(basename "$MMPROJ")" "$MMPROJ" || ok=0
  if [ "$ok" = 0 ]; then
    warn "Automatic download failed — this model is likely gated (needs a Hugging Face"
    warn "login + accepting its license). Do one of these, then re-run ./install.sh:"
    warn "  • Accept the license here:  https://huggingface.co/$HF_REPO"
    warn "      then log in:  huggingface-cli login   (and re-run ./install.sh)"
    warn "  • Or download the two files directly into $MODEL_HOME :"
    warn "        $MODEL"
    warn "          ← https://huggingface.co/$HF_REPO/resolve/main/$(basename "$MODEL")"
    warn "        $MMPROJ"
    warn "          ← https://huggingface.co/$HF_REPO/resolve/main/$(basename "$MMPROJ")"
  else
    say "Model ready."
  fi
fi

# ---- 3. Write config ------------------------------------------------------
say "Writing config.env"
cat > "$PROJ/config.env" <<ENV
# Generated by install.sh — machine-specific paths (gitignored).
LLAMA_SERVER="$BIN"
MODEL="$MODEL"
MMPROJ="$MMPROJ"
HOST="$HOST"
PORT=$PORT
CTX=$CTX
ENV

# ---- 4. Build the app -----------------------------------------------------
say "Building GemmaServer.app"
"$PROJ/app/build.sh"

echo
say "Done. Launch it with:  open \"$PROJ/GemmaServer.app\""
say "(Optional) drag GemmaServer.app into /Applications to keep it."
