#!/usr/bin/env bash
# One-shot installer for the Gemma menu-bar app.
# Sets up llama.cpp (clone + build, or reuse an existing build) and builds the app.
# You should not need to touch llama.cpp yourself.
set -euo pipefail

PROJ="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TARGET_DIR="$PROJ/llama.cpp-mainline"
BIN="$TARGET_DIR/build/bin/llama-server"

# Defaults (override by exporting before running, e.g. GEMMA_PORT=9000 ./install.sh)
MODEL="${GEMMA_MODEL:-$HOME/.lmstudio/models/google/gemma-4-12B-it-qat-q4_0-gguf/gemma-4-12b-it-qat-q4_0.gguf}"
MMPROJ="${GEMMA_MMPROJ:-$HOME/.lmstudio/models/google/gemma-4-12B-it-qat-q4_0-gguf/mmproj-gemma-4-12b-it-qat-q4_0.gguf}"
HOST="${GEMMA_HOST:-0.0.0.0}"
PORT="${GEMMA_PORT:-8080}"
CTX="${GEMMA_CTX:-32768}"

say() { printf "\033[1;36m▸ %s\033[0m\n" "$*"; }
warn() { printf "\033[1;33m! %s\033[0m\n" "$*"; }

[ "$(uname)" = "Darwin" ] || { echo "This installer is macOS-only."; exit 1; }

# ---- 1. llama.cpp ---------------------------------------------------------
if [ -x "$BIN" ]; then
  say "llama-server already built — reusing it."
elif [ -x "$HOME/work/GEMMA/llama.cpp-mainline/build/bin/llama-server" ] && [ ! -e "$TARGET_DIR" ]; then
  say "Found an existing llama.cpp build — linking it (no rebuild needed)."
  ln -s "$HOME/work/GEMMA/llama.cpp-mainline" "$TARGET_DIR"
else
  if ! command -v cmake >/dev/null 2>&1; then
    if command -v brew >/dev/null 2>&1; then
      say "Installing cmake via Homebrew…"; brew install cmake
    else
      echo "cmake is required to build llama.cpp. Install Homebrew (https://brew.sh) then re-run, or run: brew install cmake"
      exit 1
    fi
  fi
  if [ ! -d "$TARGET_DIR/.git" ] && [ ! -L "$TARGET_DIR" ]; then
    say "Cloning llama.cpp…"
    git clone --depth 1 https://github.com/ggml-org/llama.cpp "$TARGET_DIR"
  fi
  say "Building llama.cpp with Metal (this can take a few minutes)…"
  cmake -B "$TARGET_DIR/build" -S "$TARGET_DIR" \
    -DCMAKE_BUILD_TYPE=Release -DGGML_METAL=ON -DLLAMA_CURL=OFF -DLLAMA_BUILD_SERVER=ON
  cmake --build "$TARGET_DIR/build" -j --target llama-server llama-cli
fi

# ---- 2. Model check (informational) --------------------------------------
if [ ! -f "$MODEL" ]; then
  warn "Model not found at: $MODEL"
  warn "Download the Gemma GGUF (e.g. via LM Studio) or set GEMMA_MODEL, then re-run."
fi

# ---- 3. Write config ------------------------------------------------------
say "Writing config.env"
cat > "$PROJ/config.env" <<ENV
# Generated by install.sh — machine-specific paths (gitignored).
LLAMA_SERVER="$BIN"
MODEL="$MODEL"
MMPROJ="$MMPROJ"
HOST="$HOST"
PORT=$PORT
CTX=$CTX
ENV

# ---- 4. Build the app -----------------------------------------------------
say "Building GemmaServer.app"
"$PROJ/app/build.sh"

echo
say "Done. Launch it with:  open \"$PROJ/GemmaServer.app\""
say "(Optional) drag GemmaServer.app into /Applications to keep it."
