// Real client code fed with the server's censored sample responses (docs/api-samples/*.json, generated by
// server/tools/gen_api_samples.py from a seeded server): home renders the boot sample (episode cards, labels, focus keys,
// open params), the detail helpers read the series sample (season order, resume, episode states), playflow orders the
// stream samples. A server/client field rename breaks this test and server/tests/test_client_contract.py.
const fs = require('fs'), path = require('path'), vm = require('vm'), assert = require('assert');
const { el, findAll, byAttr } = require('./_fake_dom');

const root = path.join(__dirname, '../tizen-client/js');
const read = f => fs.readFileSync(path.join(root, f), 'utf8');
const sample = n => JSON.parse(fs.readFileSync(path.join(__dirname, '../docs/api-samples', n), 'utf8'));

// ---------------------------------------------------------------- home: boot sample
const gos = [];
const window = { requestAnimationFrame: f => f(), Image: function () { return el('img'); }, DZ: {} };
const DZ = window.DZ;
const boot = sample('boot.json');
// the server's home layout (homelayout.py): no `new_episodes` row any more; the client still draws any row id, so the
// episode-card coverage below feeds the `/api/row/new_episodes` sample as one more boot row
assert.deepEqual(boot.rows.map(r => r.id), ['continue', 'trending_series', 'series', 'trending_movies', 'noteworthy_movies', 'movies', 'mylist']);
assert.deepEqual(boot.rows.map(r => r.title), ['İzlemeye Devam Et', 'Haftanın Trendleri · Diziler', 'Tüm Diziler',
  'Haftanın Trendleri · Filmler', 'Dikkate Değer Filmler', 'Tüm Filmler', 'Listem']);
assert.equal(boot.heroes.length, 6, 'slider: 3 series + 3 films');
assert.deepEqual(boot.heroes.map(h => h.type), ['series', 'movie', 'series', 'movie', 'series', 'movie']);
const epRow = sample('row-new_episodes.json');
const homeData = Object.assign({}, boot, { rows: boot.rows.concat([{ id: epRow.id, title: epRow.title, loaded: true, items: epRow.items, total: epRow.total, offset: 0 }]) });
DZ.api = { profileId: () => 'p1', cachedBoot: () => homeData, boot: () => new Promise(() => {}), saveBoot() {}, img: v => v, baseUrl: () => 'http://s' };
DZ.navigation = { create: () => el('div') };
DZ.skeleton = { home: () => el('div') };
const heroCalls = [];
DZ.hero = { create: cfg => { heroCalls.push(cfg); return el('div'); } };
DZ.nav = { setRoot() {}, onFocus() {}, focusRowById() { return true; }, focusIndex() {}, currentEl() { return null; }, rowIds() { return []; }, refresh() {}, current() { return null; } };
DZ.app = { go: (n, p) => gos.push({ n, p }), confirmExit() {} };
const sandbox = { window, document: { createElement: el }, console: { log() {} }, setTimeout, clearTimeout };
vm.createContext(sandbox);
['ui/card.js', 'ui/row.js', 'screens/home.js'].forEach(f => vm.runInContext(read(f), sandbox));
const container = el('div');
DZ.screens.home.enter(container, { profile: 'p1' });

const rowEls = {};
findAll(container, 'row').forEach(r => { rowEls[r.getAttribute('data-row-id')] = r; });
assert.deepEqual(Object.keys(rowEls), homeData.rows.map(r => r.id), 'every boot row is rendered, in order');

// slider with 6 heroes: count/index reach the hero widget, left/right wrap around (hero.js draws the dots from them)
assert.equal(heroCalls[0].count, 6);
assert.equal(heroCalls[0].index, 0);
assert.equal(heroCalls[0].item.id, boot.hero.id, 'the first hero is boot.hero');
const homeState = DZ.screens.home.debugState();
homeState.moveHero(1);
assert.equal(heroCalls[heroCalls.length - 1].index, 1);
assert.equal(heroCalls[heroCalls.length - 1].item.id, boot.heroes[1].id);
homeState.moveHero(-1); homeState.moveHero(-1);
assert.equal(heroCalls[heroCalls.length - 1].index, 5, 'left from the first hero wraps to the last of 6');
assert.equal(heroCalls[heroCalls.length - 1].item.id, boot.heroes[5].id);

// every card carries a unique focus key (card_key); episode cards show their label instead of the rating
for (const r of homeData.rows) {
  const keys = findAll(rowEls[r.id], 'card').map(c => c.getAttribute('data-focus-key')).filter(Boolean);
  assert.equal(keys.length, r.items.length, r.id + ': every card has a focus key');
  assert.equal(new Set(keys).size, keys.length, r.id + ': focus keys are unique');
}
const labels = findAll(rowEls.new_episodes, 'row-card-score').map(n => n.textContent);
assert.deepEqual(labels, ['S03 B01 · Yankı', 'S01 B05 · Hat Kopuyor', 'S01 B01 · Pilot']);
assert.deepEqual(findAll(rowEls.continue, 'row-card-score').map(n => n.textContent), ['★ Puan 7.4', 'S02 B01'],
  'the movie card shows its rating, the continue episode card its label');

// episode cards are poster tiles like every other card (series poster at rest); on focus they expand to the horizontal
// preview: the real still (allowed /img size) when has_still, else the series' horizontal art (has_backdrop), else no expansion
findAll(rowEls.new_episodes, 'card').forEach(c => {
  assert(c.classList.contains('card-episode') && c.classList.contains('card-poster'), 'new_episodes card is an episode poster tile');
  assert.equal(c.dzSrc, c.dzItem.portrait, 'series poster at rest: ' + c.dzSrc);
  if (c.dzItem.has_still) assert(/\/still\?w=640&h=360$/.test(c.dzFocusSrc), 'episode still url (allowed size): ' + c.dzFocusSrc);
  else if (c.dzItem.has_backdrop) assert(/\/backdrop\?w=640&h=360$/.test(c.dzFocusSrc), 'no real still: series horizontal art: ' + c.dzFocusSrc);
  else assert(c.dzFocusSrc === '' && c.classList.contains('card-focus-effect') && !c.classList.contains('card-focus-landscape'), 'no horizontal art: no expansion');
  if (!c.dzItem.has_still) assert(!/still/.test(c.dzSrc + c.dzFocusSrc), 'the generated still placeholder is never downloaded');
});
assert(findAll(rowEls.new_episodes, 'card').some(c => c.dzItem.has_still) && findAll(rowEls.new_episodes, 'card').some(c => !c.dzItem.has_still), 'sample covers both cases');
assert(findAll(rowEls.new_episodes, 'card').some(c => c.classList.contains('card-focus-landscape')) && findAll(rowEls.new_episodes, 'card').some(c => c.classList.contains('card-focus-effect')), 'sample covers expanding and non-expanding episode cards');
assert(findAll(rowEls.continue, 'card').filter(c => c.classList.contains('card-episode')).length === 1, 'continue: one episode card (the series), one title card (the film)');
assert(findAll(rowEls.continue, 'card').every(c => c.classList.contains('card-poster')), 'continue: every card is a poster tile');
assert(findAll(rowEls.new_episodes, 'row-tile').concat(findAll(rowEls.continue, 'row-tile')).every(t => t.getAttribute('data-base-width') === '240' && /\bposter\b/.test(t.className)), 'episode rows use the 240px poster tile');
assert(findAll(rowEls.movies, 'card').every(c => c.classList.contains('card-poster')), 'title cards stay posters');

// opening: episode cards and continue cards carry the target episode, title cards do not
const open = key => { gos.length = 0; byAttr(container, 'data-focus-key', key).click(); return gos[0]; };
assert.deepEqual(open('episode:dizi-sinyal:s3:e1'), { n: 'detail', p: { id: 'dizi-sinyal', episodeId: 'dizi-sinyal:s3:e1' } });
assert.deepEqual(open('episode:dizi-sinyal:s2:e1'), { n: 'detail', p: { id: 'dizi-sinyal', episodeId: 'dizi-sinyal:s2:e1' } },
  'continue card -> resume episode through the same page');
assert.deepEqual(open('title:film-gece'), { n: 'detail', p: { id: 'film-gece' } });
assert(findAll(rowEls.continue, 'card-progress').length === 2, 'continue cards show their progress bar');
assert(findAll(rowEls.new_episodes, 'card-progress').length === 0, 'new episodes have no progress bar');

// ---------------------------------------------------------------- detail: series sample through detail.js helpers
const dsb = { window: { DZ: {} }, document: { createElement: el }, console: { log() {} }, setTimeout, clearTimeout };
vm.createContext(dsb);
vm.runInContext(read('screens/detail.js'), dsb);
const h = dsb.window.DZ.screens.detail.helpers;
const d = sample('detail-series.json');
assert.deepEqual(d.seasons.map(s => s.season), [0, 1, 2, 3], 'server lists season 0 first');
assert.deepEqual(h.sortSeasons(d.seasons).map(s => s.season), [1, 2, 3, 0], 'the client sorts specials last');
const seasons = h.sortSeasons(d.seasons);
const at = h.findEpisode(seasons, d.resume.episode_id);
assert(at && seasons[at.s].episodes[at.e].id === d.resume.episode_id, 'resume.episode_id points at a real episode');
const states = {};
seasons.forEach(s => s.episodes.forEach(e => { states[e.id] = h.epState(e, '2026-09-30'); }));
assert.equal(states['dizi-sinyal:s2:e2'], 'unavailable');
assert.equal(states['dizi-sinyal:s2:e3'], 'check');
assert.equal(states['dizi-sinyal:s3:e1'], 'ready');
const season2 = seasons.find(s => s.season === 2);
assert.equal(h.targetEpisodeIndex(season2.episodes, '2026-09-30'), 0, 'first playable unwatched episode of the season');
assert.equal(h.fmtDate(d.seasons[1].episodes[0].air_date), '1 Oca 2026');
assert(d.seasons.every(s => s.has_poster === false && /\/img\/dizi-sinyal\/portrait/.test(s.poster_url)),
  'without a season poster the series poster url is returned (client shows none)');
assert(d.seasons.every(s => s.episodes.every(e => e.still === e.still_url && typeof e.has_still === 'boolean')));
const action = d.actions[0];
assert.equal(action.kind, 'resume_episode');
assert(findEpisodeById(seasons, action.episode_id), 'the action targets a listed episode');
function findEpisodeById(list, id) { return list.some(s => s.episodes.some(e => e.id === id)); }

// series without episodes: no browser data, only the trailer action
const bare = sample('detail-series-no-episodes.json');
assert.deepEqual([bare.seasons.length, bare.actions.map(a => a.kind)], [0, ['play_trailer']]);

// ---------------------------------------------------------------- playflow: stream samples
const psb = { window: { DZ: {} }, document: { createElement: el }, console: { log() {} }, setTimeout, clearTimeout };
vm.createContext(psb);
vm.runInContext(read('playflow.js'), psb);
const pf = psb.window.DZ.playflow;
const movie = sample('streams-movie.json'), trailer = sample('streams-trailer.json');
assert.equal(pf.orderStreams(movie.streams).length, 1);
assert(movie.streams.every(s => s.attempt_token && s.url && s.label && ['hls', 'mp4', 'embed'].includes(s.type)));
assert.equal(pf.orderStreams(trailer.streams)[0].type, 'embed');
assert(typeof movie.resume_position === 'number' && typeof movie.duration === 'number');

console.log('API samples through the real client (home cards, detail helpers, playflow): OK');
