// Episode rows start playback through the loading flow (no black player screen) and keep a bounded overview in the list.
const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('assert');
function el(tag){return {tagName:tag.toUpperCase(),style:{},children:[],listeners:{},className:'',textContent:'',classList:{add(){},remove(){}},setAttribute(){},addEventListener(t,f){this.listeners[t]=f;},appendChild(n){this.children.push(n);n.parentNode=this;},removeChild(n){this.children=this.children.filter(x=>x!==n);},get firstChild(){return this.children[0];},querySelector(){return null;}};}
function find(root,cls){if((' '+root.className+' ').indexOf(' '+cls+' ')>=0)return root;for(const child of root.children||[]){const got=find(child,cls);if(got)return got;}return null;}
const longOverview=('Bu bölümün uzun açıklaması izleyiciye bölüm listesinde kısa ve okunabilir bir özet sunmalıdır. ').repeat(4);
const detail={id:'series',type:'series',title:'Dizi',overview:'Dizi özeti',genres:[],availability:{state:'ready'},seasons:[{title:'1. Sezon',episodes:[{id:'series:s1:e1',episode:1,title:'Pilot',overview:longOverview,runtime:45,availability:{state:'ready'}}]}]};
const calls=[],flows=[];
const w={requestAnimationFrame:f=>f(),Image:function(){return el('img');},DZ:{api:{profileId:()=>'',detail:()=>Promise.resolve(detail)},card:{sized:x=>x||''},skeleton:{detail:()=>el('div')},nav:{setRoot(){},onFocus(){},focusRowById(){return true;},focusIndex(){},currentEl(){return null;},refresh(){},restoreNext(){},rowIds(){return [];},current(){return null;}},playflow:{start:o=>flows.push(o)},modal:{text(){throw Error('modal should not open');}},app:{go:(name,params)=>calls.push({name,params}),back(){}}}};
vm.runInNewContext(fs.readFileSync(path.join(__dirname,'../tizen-client/js/screens/detail.js'),'utf8'),{window:w,Image:w.Image,document:{createElement:el},console:{log(){}}});
(async()=>{const root=el('div');w.DZ.screens.detail.enter(root,{id:'series'});await Promise.resolve();await Promise.resolve();const episode=find(root,'ep');const overview=find(root,'ep-ov');assert(episode&&overview);assert(overview.textContent.length<=180);assert(overview.textContent.endsWith('…'));episode.listeners.click();assert.equal(flows.length,1);assert.equal(flows[0].episodeId,'series:s1:e1');assert.equal(flows[0].itemId,'series');assert.equal(calls.length,0,'the player screen must only open after the stream is ready');console.log('TV episode direct-play and overview truncation: OK');})().catch(e=>{console.error(e);process.exitCode=1;});
