// Execute the real TV player against a deterministic AVPlay double.
const fs=require('fs'),vm=require('vm'),assert=require('assert');
function el(tag){return {tagName:tag.toUpperCase(),style:{},children:[],classList:{add(){},remove(){}},setAttribute(){},addEventListener(){},appendChild(n){this.children.push(n);n.parentNode=this;},removeChild(n){this.children=this.children.filter(x=>x!==n);n.parentNode=null;},get firstChild(){return this.children[0];}};}
const reports=[],listeners=[],seeks=[];let currentUrl='',backs=0;
const av={open(url){currentUrl=url;},setDisplayRect(){},setDisplayMethod(){},setListener(l){listeners.push(l);},prepareAsync(ok,err){if(currentUrl.includes('bad'))err('connection failed');else ok();},getDuration(){return 90000;},play(){},stop(){},close(){},seekTo(ms){seeks.push(ms);},pause(){}};
const streams=[{url:'https://video.example/bad.mp4',type:'mp4',source_id:'bad',attempt_token:'bad-token',kind:'movie',label:'A'},{url:'https://video.example/good.mp4',type:'mp4',source_id:'good',attempt_token:'good-token',kind:'movie',label:'B'}];
const w={navigator:{onLine:true},DZ:{api:{profileId:()=> 'p1',streams:()=>Promise.resolve({streams,duration:90,resume_position:37}),playbackReport:p=>{reports.push(p);return Promise.resolve({});},progress:()=>Promise.resolve({})},modal:{open(){throw Error('Should automatically try the next source');}},app:{back(){backs++;}}}};
const sandbox={window:w,document:{createElement:el,body:el('body'),documentElement:el('html')},webapis:{avplay:av},console:{log(){}},setTimeout,clearTimeout,setInterval,clearInterval,localStorage:{getItem(){return null;},setItem(){}}};
vm.runInNewContext(fs.readFileSync('tizen-client/js/screens/player.js','utf8'),sandbox);
(async()=>{const screen=w.DZ.screens.player;screen.enter(el('div'),{itemId:'movie'});await Promise.resolve();await Promise.resolve();assert.equal(reports.length,1);assert.equal(reports[0].attempt_token,'bad-token');assert.equal(currentUrl,streams[1].url);assert.deepEqual(seeks,[37000]);listeners[0].onerror('stale error');assert.equal(reports.length,1);for(let i=38;i<=49;i++)listeners[1].oncurrentplaytime(i*1000);assert.equal(reports.filter(r=>r.event==='success').length,1);assert.equal(reports[1].attempt_token,'good-token');screen.exit();listeners[1].onerror('after exit');assert.equal(reports.length,2);console.log('TV resume, source fallback, health feedback, stale callbacks: OK');})().catch(e=>{console.error(e);process.exitCode=1;w.DZ.screens.player.exit();});
